config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers, :properties, :groups
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :possible_attributes, only: [:index, :new, :show, :edit, :create, :update, :destroy] do
    member do
      get :possible_values
    end
  end
  resources :possible_attribute_values, only: [:create, :update, :destroy]
  resources :user_attribute_string_relationships, only: [:new, :create, :edit, :update, :destroy]
  resources :groups do
    member do
      get :rules, :users
    end
  end
  resources :group_attribute_string_relationships, only: [:new, :create, :edit, :update, :destroy]
      
  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
      
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/help2',   to: 'static_pages#help2'

end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name, :group_id, :possible_attribute_id

  has_many :user_group_relationships, dependent: :destroy
  has_many :users, through: :user_group_relationships
  has_many :group_attribute_string_relationships, dependent: :destroy
  has_many :possible_attributes, through: :group_attribute_string_relationships

  validates :name, presence: true,  length: { maximum: 140 },
    uniqueness: { case_sensitive: false }
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :signed_in_user, 
                only: [:index, :edit, :update, :destroy]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user,     only: [:new, :create, :edit, :update, :destroy]

  def index
    @groups = Group.paginate(page: params[:page])
    @title = "All groups"
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(params[:group])
    if @group.save
      flash[:success] = "Group created"
      update_group_users(@group)
      redirect_to @group
    else
      render 'new'
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(params[:group])
      flash[:success] = "Profile updated"
      redirect_to @group
    else
      render 'edit'
    end
  end

  def destroy
    Group.find(params[:id]).destroy
    flash[:success] = "Group destroyed."
    redirect_to groups_url
  end

  def rules
    @group = Group.find(params[:id])
    @title = "#{@group.name}'s Rules"
    @possible_attributes = PossibleAttribute.all
    @group_attribute_string_relationships = @group.group_attribute_string_relationships
    render 'show_rules'
  end

  def users
    @group = Group.find(params[:id])
    @title = "#{@group.name}'s Users"
    @users = @group.users.paginate(page: params[:page])
    render 'users/index'
  end

  private

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/views/groups/_existing_group_attribute_string_relationship.html.erb
<div class="row">
  <hr />
  <div class="span2">
    <%= val.name %>
  </div>
  <div class="span2">
    <%= val.attribute_type %>
  </div>
  <div class="span2">
    <%= group_attr_str_rel.string_operator %>
  </div>
  <div class="span2">
  	<%= group_attr_str_rel.value %>
  </div>
  <% if current_user.admin? %>
    <div class="span1">
      <%= link_to "update", edit_group_attribute_string_relationship_path(group_attr_str_rel) %>
    </div>
    <div class="span1">
      <%= link_to "clear", group_attr_str_rel, method: :delete,
                                    data: { confirm: "You sure?" } %>
    </div>
    <div class="span2"></div>
  <% else %>
    <div class="span4"></div>
  <% end %>
</div>

app/views/groups/_group.html.erb
<li>
  <%= gravatar_for current_user, size: 52 %>
  <%= link_to group.name, group %>
  <% if current_user.admin? %>
    | <%= link_to "delete", group, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/groups/_new_group_attribute_string_relationship.html.erb
<div class="row">
  <hr />
  <div class="span2">
    <%= val.name %>
  </div>
  <div class="span2">
    <%= val.attribute_type %>
  </div>
  <div class="span2">
    <b>Not set</b>
  </div>
  <div class="span3">
  	<b>Not set</b>
  </div>
  <% if current_user.admin? %>
    <div class="span1">
      <%= link_to "set", new_group_attribute_string_relationship_path(possible_attribute: val, group: @group) %>
    </div>
    <div class="span2"></div>
  <% else %>
    <div class="span3"></div>
  <% end %>
</div>

app/views/groups/edit.html.erb
<% provide(:title, "Edit group") %> 
<h1>Update group</h1>

<div class="row">
  <div class="span6 offset3">
  <%= form_for(@group) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for current_user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/groups/index.html.erb
<% provide(:title, @title) %>
<h1><%= @title %></h1>

<%= will_paginate @groups %>

<ul class="users">
  <%= render @groups %>
</ul>

<%= will_paginate @groups %>

<% if current_user.admin? && @title == "All groups" %>
  <%= link_to "Create new group", new_group_path %>
<% end %>

app/views/groups/new.html.erb
<% provide(:title, 'Create new group') %>
<h1>Create new group</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@group) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.submit "Create group", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/groups/show.html.erb
<% provide(:title, @group.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for current_user %>
        <%= @group.name %>
      </h1>
      <%= link_to "rules", rules_group_path(@group) %>
      <br />
      <%= link_to "users", users_group_path(@group) %>
    </section>
    <section>
    </section>
  </aside>
  <div class="span8">
  </div>
</div>

app/views/groups/show_rules.html.erb
<% provide(:title, @title) %>
<h1><%= @title %></h1>

<div class="row">
  <div class="span2"><h4>Name</h4></div>
  <div class="span2"><h4>Type</h4></div>
  <div class="span2"><h4>Operator</h4></div>
  <div class="span3"><h4>Value</h4></div>
  <div class="span3"></div>
</div>

<div class="row">
  <% @possible_attributes.each do |val| %>
    <% group_attr_str_rel = @group_attribute_string_relationships.find_by_possible_attribute_id(val.id) %>
    <% if (group_attr_str_rel) %>
      <%= render 'existing_group_attribute_string_relationship', val: val, group_attr_str_rel: group_attr_str_rel %>
    <% else %>
      <%= render 'new_group_attribute_string_relationship', val: val %>
    <% end %>
  <% end %>
</div>

<hr />